apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shubhamxshah/bms-backend:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 3091
          volumeMounts: 
            - name: secret 
              mountPath: /app/apps/api/.env
              subPath: .env 
            - name: secret 
              mountPath: /app/packages/database/.env 
              subPath: .env 
          env: 
          - name: DATABASE_URL
            valueFrom: 
              secretKeyRef: 
                name: bms-secret-3 
                key: DATABASE_URL
      volumes: 
        - name: secret
          secret: 
            secretName: bms-secret-3
            items: 
              - key: .env 
                path: .env 
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP # Internal service, accessible only within the cluster
  ports:
    - port: 80            # Port on which the service is exposed
      targetPort: 3091      # Port on which the container is running
  selector:
    app: backend


