apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-frontend
  labels:
    app: bms-frontend
spec:
  replicas: 1 # Number of replicas you want
  selector:
    matchLabels:
      app: bms-frontend
  template:
    metadata:
      labels:
        app: bms-frontend
    spec:
      containers:
        - name: bms-frontend
          image: shubhamxshah/bms-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bms-frontend-service
spec:
  type: LoadBalancer # Internal service, accessible only within the cluster
  ports:
    - port: 3000            # Port on which the service is exposed
      targetPort: 3000      # Port on which the container is running
  selector:
    app: bms-frontend

